# config.yml

# jailTimers: значения указываются в секундах (например, 900 = 15 минут)
jailTimers:
  "1": 900    # 900 секунд = 15 минут
  "2": 1800
  "3": 2700
  "4": 3600
  "5": 4500
  "6": 5400
  "7": 6300

# wantedCooldown: время в секундах, которое необходимо ждать между выдачами розыска (по умолчанию 30 секунд)
wantedCooldown: 30

# policefind: настройки команды поиска по спутникам
policefind:
  enabled: true
  cooldown: 1800    # 1800 секунд = 30 минут

# Настройка предмета для команды /wanteditems (материал, который будет выдаваться)
wanteditems:
  item: STICK

# Настройка функции ареста (без убийства)
arrest:
  forceTime: 1800    # Время в секундах для принудительного ареста (30 минут)
  enabled: true      # Включение/выключение команды /arrest
  radius: 5.0        # Радиус в блоках для проведения ареста (полицейский должен быть близко к преступнику)
  broadcast: true    # Отправлять ли публичное сообщение о аресте

messages:
  policecall:
    sent: "§7Вы позвонили в полицию. Ваше сообщение: {message}"
    notify: "§3Вызов полиции от §f{player} на координатах §a[{x}, {y}, {z}] Сообщение: {message}"
  policeaccept:
    error: "§cВыберите игрока из списка предупреждений!"
    accepted: "§7Вы приняли вызов от игрока {caller}"
    notify: "§7Сотрудник полиции {police} принял ваш вызов."
  wanted:
    set: "§7Розыск установлен для игрока {player} с уровнем {stars}"
    reason: "§7Причина: {reason}"
    notify: "§7Игрок {player} объявлен в розыск по причине: §a{reason}"
    interface:
      title: "§0Розыск Страница {page}"
      player_name: "§9{player}"
      stars: "§9Уровень: {stars}"
      date: "§9В розыске с:"
      reason_label: "§9Причина:"
      next_page: "§7Следующая страница →"
      prev_page: "§7← Предыдущая страница"
  arrested:
    target: "§c§l⚔ §7Вы были арестованы на {time} секунд из-за {reason}!"
    officer: "§a§l⚔ §7Вы {type} арестовали игрока {player} на {time} секунд."
    broadcast: "§c§l⚔ §7Игрок {player} был {type} арестован офицером {officer}!"
  policefind: "§3По спутникам мы видели игрока {player} на координатах §a[{x}, {y}, {z}]§3. Следующий снимок через {time} секунд. Попробуйте позже."
  jail:
    rejoin: "§c§l⚔ §7Вы все еще находитесь в тюрьме!"
    leave: "§c§l⚔ §7Вы не можете покинуть тюрьму!"

# Настройки для одной тюрьмы (для обратной совместимости)
jail:
  radius: 30.0  # Радиус тюремной зоны в блоках
  location:
    start: ""   # Координаты точки тюрьмы (start) в формате "world;x;y;z"
    end: ""     # Координаты точки освобождения (end)
  respawn:
    title: "§a§lВы пробудились!"
    subtitle: "§7Вы попали в тюрьму..."
    fadeIn: 10
    stay: 40
    fadeOut: 10
    sound: "block.anvil.land"
    soundVolume: 1.0
    soundPitch: 1.0

# Настройка нескольких тюрем
jails:
  # Центральная тюрьма
  central:
    location:
      start: ""  # Формат: "world;x;y;z" например: "world;100.5;64.0;200.5"
      end: ""    # Формат: "world;x;y;z"
    radius: 20.0
    priority: 1  # Приоритет (чем выше, тем чаще используется)

  # Тюрьма строгого режима
  maximum:
    location:
      start: ""  # Формат: "world;x;y;z"
      end: ""    # Формат: "world;x;y;z"
    radius: 15.0
    priority: 2  # Высший приоритет (для опасных преступников)

# Если baton.enabled = false, то механика полицейской дубинки (команда /wanteditems и обработчик) не регистрируется
baton:
  enabled: true