name: RefontSearch
version: 1.0.6
main: ru.lostone.refontsearch.RefontSearch
api-version: 1.16
author: RizonChik
description: Плагин для системы розыска, ареста игроков и демогрант
softdepend: [PlaceholderAPI]

commands:
  unwanted:
    description: "Снять розыск с игрока"
    usage: "/unwanted <ник>"
    permission: refontsearch.unwanted
  policefind:
    description: "Найти игрока через спутники"
    usage: "/policefind <ник>"
    permission: refontsearch.policefind
  policecall:
    description: "Вызвать полицию на помощь"
    usage: "/policecall <сообщение>"
  policeaccept:
    description: "Принять вызов полиции"
    usage: "/policeaccept <игрок>"
    permission: refontsearch.policeaccept
  wanted:
    description: "Объявить игрока в розыск или открыть список"
    usage: "/wanted [<ник> <звезды> <статья> <причина>]"
    permission: refontsearch.wanted
    aliases: [wanteds, wantedlist]
  arrest:
    description: "Арестовать игрока в розыске"
    usage: "/arrest <ник> [время] [статья] [тюрьма]"
    permission: refontsearch.arrest
  wanteditems:
    description: "Получить полицейскую дубинку"
    usage: "/wanteditems"
    permission: refontsearch.wanteditems
  setjail:
    description: "Установить координаты тюрьмы"
    usage: "/setjail [start|end]"
    permission: refontsearch.setjail
  unjail:
    description: "Освободить игрока из тюрьмы"
    usage: "/unjail <ник>"
    permission: refontsearch.unjail
  jails:
    description: "Управление несколькими тюрьмами"
    usage: "/jails <create|remove|list|setpoint|setradius> [аргументы]"
    permission: refontsearch.jails
  updatestars:
    description: "Изменить количество звезд розыска"
    usage: "/updatestars <ник> <новые_звезды>"
    permission: refontsearch.updatestars
  demorgan:
    description: "Отправить игрока в деморган"
    usage: "/demorgan <ник> <время_в_минутах> <причина>"
    permission: refontsearch.demorgan
  undemorgan:
    description: "Освободить игрока из демогрант"
    usage: "/undemorgan <ник>"
    permission: refontsearch.undemorgan
  demorganlist:
    description: "Список игроков в демогрант"
    usage: "/demorganlist"
    permission: refontsearch.demorgan.view
  setdemorgan:
    description: "Установить координаты демогрант"
    usage: "/setdemorgan [spawn|release]"
    permission: refontsearch.setdemorgan

permissions:
  refontsearch.admin:
    description: "Полные права администратора плагина"
    default: op
    children:
      - refontsearch.wanted
      - refontsearch.unwanted
      - refontsearch.arrest
      - refontsearch.updatestars
      - refontsearch.setjail
      - refontsearch.unjail
      - refontsearch.jails
      - refontsearch.policefind
      - refontsearch.policeaccept
      - refontsearch.wanteditems
      - refontsearch.demorgan
      - refontsearch.undemorgan
      - refontsearch.demorgan.view
      - refontsearch.demorgan.bypass
      - refontsearch.setdemorgan

  refontsearch.police:
    description: "Права сотрудника полиции"
    default: false
    children:
      - refontsearch.arrest
      - refontsearch.policefind
      - refontsearch.policeaccept
      - refontsearch.wanteditems

  refontsearch.moderator:
    description: "Права модератора (демогрант)"
    default: false
    children:
      - refontsearch.demorgan
      - refontsearch.undemorgan
      - refontsearch.demorgan.view

  refontsearch.wanted:
    description: "Позволяет объявлять игроков в розыск"
    default: op

  refontsearch.unwanted:
    description: "Позволяет снимать розыск с игроков"
    default: op

  refontsearch.arrest:
    description: "Позволяет арестовывать игроков"
    default: op

  refontsearch.updatestars:
    description: "Позволяет изменять количество звезд розыска"
    default: op

  refontsearch.setjail:
    description: "Позволяет устанавливать координаты тюрьмы"
    default: op

  refontsearch.unjail:
    description: "Позволяет освобождать игроков из тюрьмы"
    default: op

  refontsearch.jails:
    description: "Позволяет управлять несколькими тюрьмами"
    default: op

  refontsearch.policefind:
    description: "Позволяет искать игроков через спутники"
    default: op

  refontsearch.policeaccept:
    description: "Позволяет принимать вызовы полиции"
    default: op

  refontsearch.wanteditems:
    description: "Позволяет получать полицейское снаряжение"
    default: op

  refontsearch.demorgan:
    description: "Позволяет отправлять игроков в деморган"
    default: op

  refontsearch.undemorgan:
    description: "Позволяет освобождать игроков из демогрант"
    default: op

  refontsearch.demorgan.view:
    description: "Позволяет просматривать список игроков в демогрант"
    default: op

  refontsearch.demorgan.bypass:
    description: "Позволяет обходить ограничения демогрант"
    default: op

  refontsearch.setdemorgan:
    description: "Позволяет устанавливать координаты демогрант"
    default: op